//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.RouteImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteVertex
    {
        public long RouteVertexID { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int RouteID { get; set; }
        public long Order { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
