//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.RouteImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.RouteVertexes = new HashSet<RouteVertex>();
        }
    
        public int RouteID { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<RouteVertex> RouteVertexes { get; set; }
    }
}
