//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.Engine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonationPortalEntities : DbContext
    {
        public DonationPortalEntities()
            : base("name=DonationPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventRider> EventRiders { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteVertex> RouteVertexes { get; set; }
        public virtual DbSet<RiderMessageDonation> RiderMessageDonations { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<RecentMessage> RecentMessages { get; set; }
        public virtual DbSet<LocationVisit> LocationVisits { get; set; }
    }
}
