//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRider
    {
        public EventRider()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int EventRiderID { get; set; }
        public int EventID { get; set; }
        public string Name { get; set; }
        public string UrlSlug { get; set; }
        public double MapLatitude { get; set; }
        public double MapLongitude { get; set; }
        public byte MapZoom { get; set; }
        public double MarkerLatitude { get; set; }
        public double MarkerLongitude { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
    }
}
