//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRider
    {
        public EventRider()
        {
            this.Routes = new HashSet<Route>();
            this.RiderMessageDonations = new HashSet<RiderMessageDonation>();
            this.LocationVisits = new HashSet<LocationVisit>();
        }
    
        public int EventRiderID { get; set; }
        public int EventID { get; set; }
        public string Name { get; set; }
        public string UrlSlug { get; set; }
        public double MapLatitude { get; set; }
        public double MapLongitude { get; set; }
        public byte MapZoom { get; set; }
        public double MarkerLatitude { get; set; }
        public double MarkerLongitude { get; set; }
        public decimal DonationGoal { get; set; }
        public System.DateTime Start { get; set; }
        public string Story { get; set; }
        public string Teaser { get; set; }
        public string DurationGoal { get; set; }
        public string DistanceGoal { get; set; }
        public string PossessiveName { get; set; }
        public System.DateTime End { get; set; }
        public System.DateTime DonationStart { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
        public virtual ICollection<RiderMessageDonation> RiderMessageDonations { get; set; }
        public virtual ICollection<LocationVisit> LocationVisits { get; set; }
    }
}
