//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventRiders = new HashSet<EventRider>();
        }
    
        public int EventID { get; set; }
        public string Name { get; set; }
        public string UrlSlug { get; set; }
        public string NavigationName { get; set; }
    
        public virtual ICollection<EventRider> EventRiders { get; set; }
    }
}
