//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationVisit
    {
        public long ID { get; set; }
        public int EventRiderID { get; set; }
        public double Longtitude { get; set; }
        public double Latitude { get; set; }
        public System.DateTime DateVisited { get; set; }
    
        public virtual EventRider EventRider { get; set; }
    }
}
