//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderMessageDonation
    {
        public RiderMessageDonation()
        {
            this.RecentMessages = new HashSet<RecentMessage>();
        }
    
        public int DonationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string TransactionID { get; set; }
        public int EventRiderID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual EventRider EventRider { get; set; }
        public virtual ICollection<RecentMessage> RecentMessages { get; set; }
    }
}
