//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationPortal.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialAccount
    {
        public SocialAccount()
        {
            this.TwitterHashTags = new HashSet<TwitterHashTag>();
        }
    
        public int AccountID { get; set; }
        public string Username { get; set; }
        public int EventRiderID { get; set; }
        public string SocialType { get; set; }
    
        public virtual EventRider EventRider { get; set; }
        public virtual ICollection<TwitterHashTag> TwitterHashTags { get; set; }
    }
}
